### PR TITLE
Instant reporting.

### PR DESCRIPTION
**Pull request by JeDa**
Definitelly a lot better. :)

### CODE REVIEW

**Comment by JeDa** [comment]
I also changed some stuff. :P

**Comment by LifeMushroom** [comment]
What does instant reporting mean?

**Comment by JeDa** [comment]
Report stuff when is sent, instead of waiting to server disconnect.

Actually it's better do this due to A LOT of things.

**Comment by JeDa** [comment]
PS, this works for more than the post report plugin. It works for more stuff.

**Pull request merged**
