### PR TITLE
Do it right, or don't do it at all! (JeDa)

### PR DESCRIPTION
**Pull request by AlphaT3ch**

### CODE REVIEW

**Comment by JeDa** [comment]
>console.error
I have ded

**Comment by JeDa** [comment]
@LifeMushroom Don't merge it.

**Comment by LifeMushroom** [comment]
I think the current one is fine.

**Comment by JeDa** [comment]
Yeah, it is.

**Comment by LifeMushroom** [comment]
AlphaTech, mind explaining the difference?

**Comment by LifeMushroom** [comment]
meh

**Pull request merged**
