### PR TITLE
Cat Module

### PR DESCRIPTION
**Pull request by AlphaT3ch**

### CODE REVIEW

**Comment by LifeMushroom** [comment]
Still says I can't merge it.

**Comment by LifeMushroom** [comment]
You also removed colors and added chalk in your last PR. You readded chalk in this one. Try again. :|

**Comment by AlphaT3ch** [comment]
@LifeMushroom Oh, lol, okay, I'll resubmit :/
/me groans

**Comment by LifeMushroom** [comment]
Fork again, branch, and bla. :P

**Pull request closed without merging**
