### PR TITLE
Daemon support

### PR DESCRIPTION
**Pull request by JeDa**
Added daemon support to Modular Node.js IRC Bot :D

### CODE REVIEW

**Comment by LifeMushroom** [comment]
What's a daemon?

**Comment by JeDa** [comment]
Daemon = Like a service

With the daemon, you aren't required to have a screen (on Linux) for run it. :)

**Comment by AlphaT3ch** [comment]
Uh, what's wrong with running ``nohup node main.js &``?

**Comment by JeDa** [comment]
Nothing, but it allows check status, easy restart and easy stop options.

:P

2015-06-16 15:25 GMT-04:30, AlphaTech <notifications@github.com>:

**Pull request merged**
