### PR TITLE
Update COMMANDS.md to Accommodate "hashes"

### PR DESCRIPTION
**Pull request by AlphaT3ch**

### CODE REVIEW

**Comment by LifeMushroom** [comment]
add a space to sha512

**Comment by AlphaT3ch** [comment]
@LifeMushroom That's what you want?

**Comment by LifeMushroom** [comment]
No. Yours says ####shawhatever. Make it #### shawhatever

**Comment by AlphaT3ch** [comment]
ohhhh, 'k

**Comment by AlphaT3ch** [comment]
@LifeMushroom done

**Pull request merged**
